-- Migration: Create agent_prompts table and add active_prompt_version to agents
-- Description: Enables versioned prompt specifications generated by Prompt Builder

CREATE TABLE IF NOT EXISTS agent_prompts (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    prompt_md TEXT NOT NULL,
    guardrails_json TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(agent_id, version),
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_agent_prompts_agent_id ON agent_prompts(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_prompts_version ON agent_prompts(version);
CREATE INDEX IF NOT EXISTS idx_agent_prompts_created_at ON agent_prompts(created_at);

-- Add active_prompt_version column to agents table (if not exists)
-- This column stores which version of the generated prompt is currently active
-- NULL means no generated prompt is active (using system_message instead)
ALTER TABLE agents ADD COLUMN active_prompt_version INTEGER NULL;
